PKGS  ?= fish openssh rsync neovim
PROG  ?= bash
USER  ?= loongson
SH    ?= /bin/fish

VOLS  := $(realpath ./home):/home \
         $(realpath ./ssh):/etc/ssh \
         $(realpath ./sudoers):/etc/sudoers \
         $(realpath ./pacman.conf):/etc/pacman.conf \
         $(realpath ./pacman.d):/etc/pacman.d

PORTS   ?= 2222:22
EXPOSES ?= 6000-7000 # X forward
