NAME  ?= labuild
PKGS  ?= fish openssh rsync neovim neovim-symlinks
PROG  ?= bash
USER  ?= loongson
SH    ?= /bin/fish

VOLS  := ./home:/home \
	 ./ssh:/etc/ssh \
	 ./sudoers:/etc/sudoers \
	 ./pacman.conf:/etc/pacman.conf \
	 ./pacman.d:/etc/pacman.d

PORTS   := 2222:22
EXPOSES := 6000-7000
